In [18]:
## Homework 3 by Andres Candido

import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

# 2. Create a vector with values ranging from 10 to 49

vector = np.arange(10, 50)
print(vector)

# 3. Reverse a vector (first element becomes last)

reverse_vector = vector[::-1]
print(reverse_vector)

# 4. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3, 3)
print(matrix)

# 5. Create a random vector of size 30 and find the mean value [use uniform random numbers between 0.0 and 1.0]

vector = np.random.uniform(0.0, 1.0, 30)
mean_value = np.mean(vector)
print(vector)
print(mean_value)

# 6. Create a 2d array with 1 on the border and 0 inside

array = np.zeros((7, 7))
# Set the border values to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

# 7. Create random vector of size 10 and replace the maximum value by 0. [use uniform integer random numbers between 0 and 50]

vector2 = np.random.randint(0, 50, 10)
print(vector2)
# Find the index of the maximum value in the vector
max_index = np.argmax(vector2)
# Replace the maximum value with 0
np.put(vector2, max_index, 0)
print(vector2)

# 8. Create an array with a checkerboard pattern of 0 and 1 of size 8x8

array2 = np.ones((8, 8))
# Set every other value to 0
array2[::2, ::2] = 0
array2[1::2, 1::2] = 0
print(array2)

# 9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (using L2-norm) [use uniform random numbers between 0.0 and 1.0]

# Create a random vector with shape (100, 2)
vector = np.random.rand(100, 2)
# Calculate pairwise distances between points
distances = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        distances[i, j] = np.linalg.norm(vector[i] - vector[j])
print(distances)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0.35513541 0.93238022 0.08273613 0.01274628 0.03979183 0.6969824
 0.39765873 0.36784253 0.45995344 0.8070204  0.25208736 0.77042242
 0.14406647 0.51922018 0.63719887 0.68528098 0.20237666 0.89013791
 0.38298813 0.92494869 0.6986445  0.91112987 0.968292   0.26460481
 0.142209   0.68686368 0.13058869 0.71356995 0.71080379 0.61324524]
0.5133642194050486
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[ 5 26 23 16 33 39 34  9 43  8]
[ 5 26 23 16 33 39 34  9  0  8]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]